### ISSUE TITLE
Getting errors when using newer version of Android sdk

### ISSUE THREAD

**Issue by micky2be** [ludei/webview-plus#45]
Sadly in my apps I need a newer sdk than the version 19.
While everything works fine on a 4.4.2 device I get the following error on a 5.0.2 device:
```
FATAL EXCEPTION: main
Process: jp.company.app, PID: 7671
java.lang.RuntimeException: Unable to start activity ComponentInfo{jp.company.app/jp.company.app.App}: android.webkit.MustOverrideException: abstract function called: must be overriden!
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: android.webkit.MustOverrideException: abstract function called: must be overriden!
	at android.webkit.WebSettings.setAcceptThirdPartyCookies(WebSettings.java:509)
	at com.android.webview.chromium.CookieManagerAdapter.setAcceptThirdPartyCookies(CookieManagerAdapter.java:50)
	at org.apache.cordova.CordovaWebView.initWebViewSettings(CordovaWebView.java:200)
	at org.apache.cordova.CordovaWebView.init(CordovaWebView.java:164)
	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:345)
	at org.apache.cordova.CordovaActivity.init(CordovaActivity.java:320)
	at jp.company.app.App.onCreate(App.java:31)
	at android.app.Activity.performCreate(Activity.java:5933)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
	... 10 more
```

Any idea how I could fix it?
Having the source of WebView+ could help

**Comment by redde81** [comment]
+1 on this, getting the same error on Android 5.x when using WebView+

**Comment by MayankLogiciel** [comment]
+1, app not installing on lollypop build with WebView+

**Comment by MayankLogiciel** [comment]
does creators of WebView+ stopped supporting this project?
